//
// Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
//
// On Tue Nov  3 12:59:15 EST 2015
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTbWidthChangeFIFO(CLK,
			   RST_N);
  input  CLK;
  input  RST_N;

  // register state
  reg [15 : 0] state;
  reg [15 : 0] state$D_IN;
  wire state$EN;

  // ports of submodule wc_fifo_0
  wire [51 : 0] wc_fifo_0$portA_request_put, wc_fifo_0$portB_request_put;
  wire [31 : 0] wc_fifo_0$portA_response_get;
  wire wc_fifo_0$EN_portAClear,
       wc_fifo_0$EN_portA_request_put,
       wc_fifo_0$EN_portA_response_get,
       wc_fifo_0$EN_portBClear,
       wc_fifo_0$EN_portB_request_put,
       wc_fifo_0$EN_portB_response_get,
       wc_fifo_0$RDY_portA_request_put,
       wc_fifo_0$RDY_portA_response_get;

  // ports of submodule wc_fifo_1
  wire [51 : 0] wc_fifo_1$portA_request_put, wc_fifo_1$portB_request_put;
  wire [31 : 0] wc_fifo_1$portA_response_get;
  wire wc_fifo_1$EN_portAClear,
       wc_fifo_1$EN_portA_request_put,
       wc_fifo_1$EN_portA_response_get,
       wc_fifo_1$EN_portBClear,
       wc_fifo_1$EN_portB_request_put,
       wc_fifo_1$EN_portB_response_get,
       wc_fifo_1$RDY_portA_request_put,
       wc_fifo_1$RDY_portA_response_get;

  // ports of submodule wc_fifo_2
  wire [51 : 0] wc_fifo_2$portA_request_put, wc_fifo_2$portB_request_put;
  wire [31 : 0] wc_fifo_2$portA_response_get;
  wire wc_fifo_2$EN_portAClear,
       wc_fifo_2$EN_portA_request_put,
       wc_fifo_2$EN_portA_response_get,
       wc_fifo_2$EN_portBClear,
       wc_fifo_2$EN_portB_request_put,
       wc_fifo_2$EN_portB_response_get,
       wc_fifo_2$RDY_portA_request_put,
       wc_fifo_2$RDY_portA_response_get;

  // ports of submodule wc_fifo_3
  wire [51 : 0] wc_fifo_3$portA_request_put, wc_fifo_3$portB_request_put;
  wire [31 : 0] wc_fifo_3$portA_response_get;
  wire wc_fifo_3$EN_portAClear,
       wc_fifo_3$EN_portA_request_put,
       wc_fifo_3$EN_portA_response_get,
       wc_fifo_3$EN_portBClear,
       wc_fifo_3$EN_portB_request_put,
       wc_fifo_3$EN_portB_response_get,
       wc_fifo_3$RDY_portA_request_put,
       wc_fifo_3$RDY_portA_response_get;

  // ports of submodule wc_fifo_4
  wire [51 : 0] wc_fifo_4$portA_request_put, wc_fifo_4$portB_request_put;
  wire wc_fifo_4$EN_portAClear,
       wc_fifo_4$EN_portA_request_put,
       wc_fifo_4$EN_portA_response_get,
       wc_fifo_4$EN_portBClear,
       wc_fifo_4$EN_portB_request_put,
       wc_fifo_4$EN_portB_response_get,
       wc_fifo_4$RDY_portA_request_put;

  // ports of submodule wc_fifo_5
  wire [51 : 0] wc_fifo_5$portA_request_put, wc_fifo_5$portB_request_put;
  wire wc_fifo_5$EN_portAClear,
       wc_fifo_5$EN_portA_request_put,
       wc_fifo_5$EN_portA_response_get,
       wc_fifo_5$EN_portBClear,
       wc_fifo_5$EN_portB_request_put,
       wc_fifo_5$EN_portB_response_get,
       wc_fifo_5$RDY_portA_request_put;

  // ports of submodule wc_fifo_6
  wire [51 : 0] wc_fifo_6$portA_request_put, wc_fifo_6$portB_request_put;
  wire wc_fifo_6$EN_portAClear,
       wc_fifo_6$EN_portA_request_put,
       wc_fifo_6$EN_portA_response_get,
       wc_fifo_6$EN_portBClear,
       wc_fifo_6$EN_portB_request_put,
       wc_fifo_6$EN_portB_response_get,
       wc_fifo_6$RDY_portA_request_put;

  // ports of submodule wc_fifo_7
  wire [51 : 0] wc_fifo_7$portA_request_put, wc_fifo_7$portB_request_put;
  wire wc_fifo_7$EN_portAClear,
       wc_fifo_7$EN_portA_request_put,
       wc_fifo_7$EN_portA_response_get,
       wc_fifo_7$EN_portBClear,
       wc_fifo_7$EN_portB_request_put,
       wc_fifo_7$EN_portB_response_get,
       wc_fifo_7$RDY_portA_request_put;

  // rule scheduling signals
  wire CAN_FIRE_RL_done,
       CAN_FIRE_RL_step0,
       CAN_FIRE_RL_step1,
       CAN_FIRE_RL_step2,
       CAN_FIRE_RL_step3,
       CAN_FIRE_RL_step4,
       CAN_FIRE_RL_step5,
       WILL_FIRE_RL_done,
       WILL_FIRE_RL_step0,
       WILL_FIRE_RL_step1,
       WILL_FIRE_RL_step2,
       WILL_FIRE_RL_step3,
       WILL_FIRE_RL_step4,
       WILL_FIRE_RL_step5;

  // remaining internal signals
  wire wc_fifo_1_RDY_portA_request_put_AND_wc_fifo_2__ETC___d16;

  // submodule wc_fifo_0
  mkWCFIFO wc_fifo_0(.CLK(CLK),
		     .RST_N(RST_N),
		     .portA_request_put(wc_fifo_0$portA_request_put),
		     .portB_request_put(wc_fifo_0$portB_request_put),
		     .EN_portA_request_put(wc_fifo_0$EN_portA_request_put),
		     .EN_portA_response_get(wc_fifo_0$EN_portA_response_get),
		     .EN_portB_request_put(wc_fifo_0$EN_portB_request_put),
		     .EN_portB_response_get(wc_fifo_0$EN_portB_response_get),
		     .EN_portAClear(wc_fifo_0$EN_portAClear),
		     .EN_portBClear(wc_fifo_0$EN_portBClear),
		     .RDY_portA_request_put(wc_fifo_0$RDY_portA_request_put),
		     .portA_response_get(wc_fifo_0$portA_response_get),
		     .RDY_portA_response_get(wc_fifo_0$RDY_portA_response_get),
		     .RDY_portB_request_put(),
		     .portB_response_get(),
		     .RDY_portB_response_get());

  // submodule wc_fifo_1
  mkWCFIFO wc_fifo_1(.CLK(CLK),
		     .RST_N(RST_N),
		     .portA_request_put(wc_fifo_1$portA_request_put),
		     .portB_request_put(wc_fifo_1$portB_request_put),
		     .EN_portA_request_put(wc_fifo_1$EN_portA_request_put),
		     .EN_portA_response_get(wc_fifo_1$EN_portA_response_get),
		     .EN_portB_request_put(wc_fifo_1$EN_portB_request_put),
		     .EN_portB_response_get(wc_fifo_1$EN_portB_response_get),
		     .EN_portAClear(wc_fifo_1$EN_portAClear),
		     .EN_portBClear(wc_fifo_1$EN_portBClear),
		     .RDY_portA_request_put(wc_fifo_1$RDY_portA_request_put),
		     .portA_response_get(wc_fifo_1$portA_response_get),
		     .RDY_portA_response_get(wc_fifo_1$RDY_portA_response_get),
		     .RDY_portB_request_put(),
		     .portB_response_get(),
		     .RDY_portB_response_get());

  // submodule wc_fifo_2
  mkWCFIFO wc_fifo_2(.CLK(CLK),
		     .RST_N(RST_N),
		     .portA_request_put(wc_fifo_2$portA_request_put),
		     .portB_request_put(wc_fifo_2$portB_request_put),
		     .EN_portA_request_put(wc_fifo_2$EN_portA_request_put),
		     .EN_portA_response_get(wc_fifo_2$EN_portA_response_get),
		     .EN_portB_request_put(wc_fifo_2$EN_portB_request_put),
		     .EN_portB_response_get(wc_fifo_2$EN_portB_response_get),
		     .EN_portAClear(wc_fifo_2$EN_portAClear),
		     .EN_portBClear(wc_fifo_2$EN_portBClear),
		     .RDY_portA_request_put(wc_fifo_2$RDY_portA_request_put),
		     .portA_response_get(wc_fifo_2$portA_response_get),
		     .RDY_portA_response_get(wc_fifo_2$RDY_portA_response_get),
		     .RDY_portB_request_put(),
		     .portB_response_get(),
		     .RDY_portB_response_get());

  // submodule wc_fifo_3
  mkWCFIFO wc_fifo_3(.CLK(CLK),
		     .RST_N(RST_N),
		     .portA_request_put(wc_fifo_3$portA_request_put),
		     .portB_request_put(wc_fifo_3$portB_request_put),
		     .EN_portA_request_put(wc_fifo_3$EN_portA_request_put),
		     .EN_portA_response_get(wc_fifo_3$EN_portA_response_get),
		     .EN_portB_request_put(wc_fifo_3$EN_portB_request_put),
		     .EN_portB_response_get(wc_fifo_3$EN_portB_response_get),
		     .EN_portAClear(wc_fifo_3$EN_portAClear),
		     .EN_portBClear(wc_fifo_3$EN_portBClear),
		     .RDY_portA_request_put(wc_fifo_3$RDY_portA_request_put),
		     .portA_response_get(wc_fifo_3$portA_response_get),
		     .RDY_portA_response_get(wc_fifo_3$RDY_portA_response_get),
		     .RDY_portB_request_put(),
		     .portB_response_get(),
		     .RDY_portB_response_get());

  // submodule wc_fifo_4
  mkWCFIFO wc_fifo_4(.CLK(CLK),
		     .RST_N(RST_N),
		     .portA_request_put(wc_fifo_4$portA_request_put),
		     .portB_request_put(wc_fifo_4$portB_request_put),
		     .EN_portA_request_put(wc_fifo_4$EN_portA_request_put),
		     .EN_portA_response_get(wc_fifo_4$EN_portA_response_get),
		     .EN_portB_request_put(wc_fifo_4$EN_portB_request_put),
		     .EN_portB_response_get(wc_fifo_4$EN_portB_response_get),
		     .EN_portAClear(wc_fifo_4$EN_portAClear),
		     .EN_portBClear(wc_fifo_4$EN_portBClear),
		     .RDY_portA_request_put(wc_fifo_4$RDY_portA_request_put),
		     .portA_response_get(),
		     .RDY_portA_response_get(),
		     .RDY_portB_request_put(),
		     .portB_response_get(),
		     .RDY_portB_response_get());

  // submodule wc_fifo_5
  mkWCFIFO wc_fifo_5(.CLK(CLK),
		     .RST_N(RST_N),
		     .portA_request_put(wc_fifo_5$portA_request_put),
		     .portB_request_put(wc_fifo_5$portB_request_put),
		     .EN_portA_request_put(wc_fifo_5$EN_portA_request_put),
		     .EN_portA_response_get(wc_fifo_5$EN_portA_response_get),
		     .EN_portB_request_put(wc_fifo_5$EN_portB_request_put),
		     .EN_portB_response_get(wc_fifo_5$EN_portB_response_get),
		     .EN_portAClear(wc_fifo_5$EN_portAClear),
		     .EN_portBClear(wc_fifo_5$EN_portBClear),
		     .RDY_portA_request_put(wc_fifo_5$RDY_portA_request_put),
		     .portA_response_get(),
		     .RDY_portA_response_get(),
		     .RDY_portB_request_put(),
		     .portB_response_get(),
		     .RDY_portB_response_get());

  // submodule wc_fifo_6
  mkWCFIFO wc_fifo_6(.CLK(CLK),
		     .RST_N(RST_N),
		     .portA_request_put(wc_fifo_6$portA_request_put),
		     .portB_request_put(wc_fifo_6$portB_request_put),
		     .EN_portA_request_put(wc_fifo_6$EN_portA_request_put),
		     .EN_portA_response_get(wc_fifo_6$EN_portA_response_get),
		     .EN_portB_request_put(wc_fifo_6$EN_portB_request_put),
		     .EN_portB_response_get(wc_fifo_6$EN_portB_response_get),
		     .EN_portAClear(wc_fifo_6$EN_portAClear),
		     .EN_portBClear(wc_fifo_6$EN_portBClear),
		     .RDY_portA_request_put(wc_fifo_6$RDY_portA_request_put),
		     .portA_response_get(),
		     .RDY_portA_response_get(),
		     .RDY_portB_request_put(),
		     .portB_response_get(),
		     .RDY_portB_response_get());

  // submodule wc_fifo_7
  mkWCFIFO wc_fifo_7(.CLK(CLK),
		     .RST_N(RST_N),
		     .portA_request_put(wc_fifo_7$portA_request_put),
		     .portB_request_put(wc_fifo_7$portB_request_put),
		     .EN_portA_request_put(wc_fifo_7$EN_portA_request_put),
		     .EN_portA_response_get(wc_fifo_7$EN_portA_response_get),
		     .EN_portB_request_put(wc_fifo_7$EN_portB_request_put),
		     .EN_portB_response_get(wc_fifo_7$EN_portB_response_get),
		     .EN_portAClear(wc_fifo_7$EN_portAClear),
		     .EN_portBClear(wc_fifo_7$EN_portBClear),
		     .RDY_portA_request_put(wc_fifo_7$RDY_portA_request_put),
		     .portA_response_get(),
		     .RDY_portA_response_get(),
		     .RDY_portB_request_put(),
		     .portB_response_get(),
		     .RDY_portB_response_get());

  // rule RL_step0
  assign CAN_FIRE_RL_step0 = state == 16'd0 ;
  assign WILL_FIRE_RL_step0 = CAN_FIRE_RL_step0 ;

  // rule RL_step1
  assign CAN_FIRE_RL_step1 =
	     wc_fifo_0$RDY_portA_request_put &&
	     wc_fifo_1_RDY_portA_request_put_AND_wc_fifo_2__ETC___d16 &&
	     state == 16'd1 ;
  assign WILL_FIRE_RL_step1 = CAN_FIRE_RL_step1 ;

  // rule RL_step2
  assign CAN_FIRE_RL_step2 =
	     wc_fifo_0$RDY_portA_response_get &&
	     wc_fifo_1$RDY_portA_response_get &&
	     state == 16'd2 ;
  assign WILL_FIRE_RL_step2 = CAN_FIRE_RL_step2 ;

  // rule RL_step3
  assign CAN_FIRE_RL_step3 =
	     wc_fifo_0$RDY_portA_request_put &&
	     wc_fifo_1$RDY_portA_request_put &&
	     state == 16'd3 ;
  assign WILL_FIRE_RL_step3 = CAN_FIRE_RL_step3 ;

  // rule RL_step4
  assign CAN_FIRE_RL_step4 =
	     wc_fifo_0$RDY_portA_response_get &&
	     wc_fifo_1$RDY_portA_response_get &&
	     state == 16'd4 ;
  assign WILL_FIRE_RL_step4 = CAN_FIRE_RL_step4 ;

  // rule RL_step5
  assign CAN_FIRE_RL_step5 =
	     wc_fifo_2$RDY_portA_response_get &&
	     wc_fifo_3$RDY_portA_response_get &&
	     state == 16'd5 ;
  assign WILL_FIRE_RL_step5 = CAN_FIRE_RL_step5 ;

  // rule RL_done
  assign CAN_FIRE_RL_done = state == 16'd6 ;
  assign WILL_FIRE_RL_done = CAN_FIRE_RL_done ;

  // register state
  always@(WILL_FIRE_RL_step0 or
	  WILL_FIRE_RL_step1 or
	  WILL_FIRE_RL_step2 or
	  WILL_FIRE_RL_step3 or WILL_FIRE_RL_step4 or WILL_FIRE_RL_step5)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_step0: state$D_IN = 16'd1;
      WILL_FIRE_RL_step1: state$D_IN = 16'd2;
      WILL_FIRE_RL_step2: state$D_IN = 16'd3;
      WILL_FIRE_RL_step3: state$D_IN = 16'd4;
      WILL_FIRE_RL_step4: state$D_IN = 16'd5;
      WILL_FIRE_RL_step5: state$D_IN = 16'd6;
      default: state$D_IN = 16'b1010101010101010 /* unspecified value */ ;
    endcase
  end
  assign state$EN =
	     WILL_FIRE_RL_step0 || WILL_FIRE_RL_step1 || WILL_FIRE_RL_step2 ||
	     WILL_FIRE_RL_step3 ||
	     WILL_FIRE_RL_step4 ||
	     WILL_FIRE_RL_step5 ;

  // submodule wc_fifo_0
  assign wc_fifo_0$portA_request_put =
	     WILL_FIRE_RL_step1 ? 52'hC001011223344 : 52'hC001422334455 ;
  assign wc_fifo_0$portB_request_put = 52'h0 ;
  assign wc_fifo_0$EN_portA_request_put =
	     WILL_FIRE_RL_step1 || WILL_FIRE_RL_step3 ;
  assign wc_fifo_0$EN_portA_response_get =
	     WILL_FIRE_RL_step4 || WILL_FIRE_RL_step2 ;
  assign wc_fifo_0$EN_portB_request_put = 1'b0 ;
  assign wc_fifo_0$EN_portB_response_get = 1'b0 ;
  assign wc_fifo_0$EN_portAClear = 1'b0 ;
  assign wc_fifo_0$EN_portBClear = 1'b0 ;

  // submodule wc_fifo_1
  assign wc_fifo_1$portA_request_put =
	     WILL_FIRE_RL_step1 ? 52'hC001011223344 : 52'hC0014BBBBBBBB ;
  assign wc_fifo_1$portB_request_put = 52'h0 ;
  assign wc_fifo_1$EN_portA_request_put =
	     WILL_FIRE_RL_step1 || WILL_FIRE_RL_step3 ;
  assign wc_fifo_1$EN_portA_response_get =
	     WILL_FIRE_RL_step4 || WILL_FIRE_RL_step2 ;
  assign wc_fifo_1$EN_portB_request_put = 1'b0 ;
  assign wc_fifo_1$EN_portB_response_get = 1'b0 ;
  assign wc_fifo_1$EN_portAClear = 1'b0 ;
  assign wc_fifo_1$EN_portBClear = 1'b0 ;

  // submodule wc_fifo_2
  assign wc_fifo_2$portA_request_put = 52'hC001011223344 ;
  assign wc_fifo_2$portB_request_put = 52'h0 ;
  assign wc_fifo_2$EN_portA_request_put = CAN_FIRE_RL_step1 ;
  assign wc_fifo_2$EN_portA_response_get = CAN_FIRE_RL_step5 ;
  assign wc_fifo_2$EN_portB_request_put = 1'b0 ;
  assign wc_fifo_2$EN_portB_response_get = 1'b0 ;
  assign wc_fifo_2$EN_portAClear = 1'b0 ;
  assign wc_fifo_2$EN_portBClear = 1'b0 ;

  // submodule wc_fifo_3
  assign wc_fifo_3$portA_request_put = 52'hC001011223344 ;
  assign wc_fifo_3$portB_request_put = 52'h0 ;
  assign wc_fifo_3$EN_portA_request_put = CAN_FIRE_RL_step1 ;
  assign wc_fifo_3$EN_portA_response_get = CAN_FIRE_RL_step5 ;
  assign wc_fifo_3$EN_portB_request_put = 1'b0 ;
  assign wc_fifo_3$EN_portB_response_get = 1'b0 ;
  assign wc_fifo_3$EN_portAClear = 1'b0 ;
  assign wc_fifo_3$EN_portBClear = 1'b0 ;

  // submodule wc_fifo_4
  assign wc_fifo_4$portA_request_put = 52'hC001011223344 ;
  assign wc_fifo_4$portB_request_put = 52'h0 ;
  assign wc_fifo_4$EN_portA_request_put = CAN_FIRE_RL_step1 ;
  assign wc_fifo_4$EN_portA_response_get = 1'b0 ;
  assign wc_fifo_4$EN_portB_request_put = 1'b0 ;
  assign wc_fifo_4$EN_portB_response_get = 1'b0 ;
  assign wc_fifo_4$EN_portAClear = 1'b0 ;
  assign wc_fifo_4$EN_portBClear = 1'b0 ;

  // submodule wc_fifo_5
  assign wc_fifo_5$portA_request_put = 52'hC001011223344 ;
  assign wc_fifo_5$portB_request_put = 52'h0 ;
  assign wc_fifo_5$EN_portA_request_put = CAN_FIRE_RL_step1 ;
  assign wc_fifo_5$EN_portA_response_get = 1'b0 ;
  assign wc_fifo_5$EN_portB_request_put = 1'b0 ;
  assign wc_fifo_5$EN_portB_response_get = 1'b0 ;
  assign wc_fifo_5$EN_portAClear = 1'b0 ;
  assign wc_fifo_5$EN_portBClear = 1'b0 ;

  // submodule wc_fifo_6
  assign wc_fifo_6$portA_request_put = 52'hC001011223344 ;
  assign wc_fifo_6$portB_request_put = 52'h0 ;
  assign wc_fifo_6$EN_portA_request_put = CAN_FIRE_RL_step1 ;
  assign wc_fifo_6$EN_portA_response_get = 1'b0 ;
  assign wc_fifo_6$EN_portB_request_put = 1'b0 ;
  assign wc_fifo_6$EN_portB_response_get = 1'b0 ;
  assign wc_fifo_6$EN_portAClear = 1'b0 ;
  assign wc_fifo_6$EN_portBClear = 1'b0 ;

  // submodule wc_fifo_7
  assign wc_fifo_7$portA_request_put = 52'hC001011223344 ;
  assign wc_fifo_7$portB_request_put = 52'h0 ;
  assign wc_fifo_7$EN_portA_request_put = CAN_FIRE_RL_step1 ;
  assign wc_fifo_7$EN_portA_response_get = 1'b0 ;
  assign wc_fifo_7$EN_portB_request_put = 1'b0 ;
  assign wc_fifo_7$EN_portB_response_get = 1'b0 ;
  assign wc_fifo_7$EN_portAClear = 1'b0 ;
  assign wc_fifo_7$EN_portBClear = 1'b0 ;

  // remaining internal signals
  assign wc_fifo_1_RDY_portA_request_put_AND_wc_fifo_2__ETC___d16 =
	     wc_fifo_1$RDY_portA_request_put &&
	     wc_fifo_2$RDY_portA_request_put &&
	     wc_fifo_3$RDY_portA_request_put &&
	     wc_fifo_4$RDY_portA_request_put &&
	     wc_fifo_5$RDY_portA_request_put &&
	     wc_fifo_6$RDY_portA_request_put &&
	     wc_fifo_7$RDY_portA_request_put ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        state <= `BSV_ASSIGNMENT_DELAY 16'd0;
      end
    else
      begin
        if (state$EN) state <= `BSV_ASSIGNMENT_DELAY state$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    state = 16'hAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_step2)
	$display("BRAM01 Read = %x %x",
		 $unsigned(wc_fifo_0$portA_response_get),
		 $unsigned(wc_fifo_1$portA_response_get));
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_step4)
	$display("BRAM01 Read = %x %x",
		 $unsigned(wc_fifo_0$portA_response_get),
		 $unsigned(wc_fifo_1$portA_response_get));
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_step5)
	$display("BRAM23 Read = %x %x",
		 $unsigned(wc_fifo_2$portA_response_get),
		 $unsigned(wc_fifo_3$portA_response_get));
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_done) $display("TESTS FINISHED");
    if (RST_N != `BSV_RESET_VALUE) if (WILL_FIRE_RL_done) $finish(32'd0);
  end
  // synopsys translate_on
endmodule  // mkTbWidthChangeFIFO

